"""Abstract acquisition reader interface (from petakit)."""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator
import json

import numpy as np
import tifffile


@dataclass
class Metadata:
    """Microscope acquisition parameters."""
    dxy: float          # Pixel size in um
    dz: float           # Z-step in um
    na: float           # Numerical aperture
    magnification: float
    channels: list[str] # Channel names (e.g., ["405", "488", "561"])
    nz: int             # Number of z-planes
    nt: int             # Number of timepoints

    @classmethod
    def from_acquisition_json(cls, path: Path, channels: list[str]) -> "Metadata":
        """Parse acquisition_parameters.json."""
        try:
            with open(path, encoding="utf-8") as f:
                params = json.load(f)
        except FileNotFoundError:
            raise FileNotFoundError(
                f"acquisition_parameters.json not found at {path}. "
                "This file is required and is generated by the Cephla "
                "acquisition software."
            ) from None

        _required = ["objective", "sensor_pixel_size_um", "dz(um)", "Nz"]
        missing = [k for k in _required if k not in params]
        if missing:
            raise ValueError(
                f"acquisition_parameters.json is missing required fields: "
                f"{missing}"
            )
        obj = params["objective"]
        for key in ("magnification", "NA"):
            if key not in obj:
                raise ValueError(
                    f"'objective' in acquisition_parameters.json is missing "
                    f"required field: '{key}'"
                )

        mag = obj["magnification"]
        sensor_px = params["sensor_pixel_size_um"]

        return cls(
            dxy=sensor_px / mag,
            dz=params["dz(um)"],
            na=obj["NA"],
            magnification=mag,
            channels=channels,
            nz=params["Nz"],
            nt=params.get("Nt", 1),
        )


@dataclass
class FOV:
    """Field of view identifier."""
    region: str
    index: int
    timepoint: int = 0

    def __str__(self) -> str:
        return f"{self.region}_{self.index}"


@dataclass(frozen=True)
class FrameRef:
    """Reference to a single 2D frame inside an acquisition.

    page_idx is None for single-page TIFFs (read whole file) and an integer
    for multi-page TIFFs (read that page).
    """
    fov: FOV
    frame_idx: int
    file_path: Path
    page_idx: int | None


class AcquisitionReader(ABC):
    """Abstract base for acquisition format readers.

    Subclasses must implement:
        - format_name: str property
        - iter_fovs(): Iterator[FOV]
        - get_stack(fov, channel): np.ndarray
    """

    def __init__(self, root: Path, metadata: Metadata):
        self.root = root
        self.metadata = metadata

    @property
    @abstractmethod
    def format_name(self) -> str:
        pass

    @abstractmethod
    def iter_fovs(self) -> Iterator[FOV]:
        pass

    @abstractmethod
    def get_stack(self, fov: FOV, channel: str) -> np.ndarray:
        """Load a z-stack for given FOV and channel. Returns (Z, Y, X) array."""
        pass

    def get_frame(self, fov: FOV, channel: str, z_idx: int) -> np.ndarray:
        """Load a single 2D frame. Default: load full stack and index."""
        stack = self.get_stack(fov, channel)
        if stack.ndim == 3:
            return stack[min(z_idx, stack.shape[0] - 1)]
        return stack

    def iter_frames_for_fov(self, fov: FOV, channel: str) -> Iterator["FrameRef"]:
        """Yield FrameRef for every 2D frame in this FOV+channel, in frame_idx order.

        Subclasses must override.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__} does not implement iter_frames_for_fov"
        )

    def n_frames_per_fov(self, fov: FOV, channel: str) -> int:
        """Number of 2D frames for one FOV+channel.

        Subclasses must override.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__} does not implement n_frames_per_fov"
        )

    def iter_frames(self, channel: str):
        """Yield (fov, z_idx, file_path, page_idx) for every 2D frame.

        file_path + page_idx allow direct tifffile.imread(path, key=page)
        without loading full stacks — critical for parallel workers.
        Subclasses should override for efficiency.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__} does not support iter_frames"
        )

    @property
    def frame_shape(self) -> tuple:
        """Return (H, W) of a single frame."""
        raise NotImplementedError

    @property
    def frame_dtype(self):
        """Return dtype of frames."""
        raise NotImplementedError

    def get_all_channels(self, fov: FOV) -> dict[str, np.ndarray]:
        return {ch: self.get_stack(fov, ch) for ch in self.metadata.channels}

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}("
            f"format='{self.format_name}', "
            f"fovs={sum(1 for _ in self.iter_fovs())}, "
            f"channels={self.metadata.channels})"
        )
